CREATE DATABASE IF NOT EXISTS Game;
USE Game; 

<<<<<<< HEAD
DROP TABLE Inventory;
TRUNCATE TABLE Items;
TRUNCATE TABLE Players;
=======
DROP TABLE IF EXISTS Inventory;
>>>>>>> aba6947f00c28937f653857617272d5894dee504

CREATE TABLE IF NOT EXISTS Players ( 
	Player_id INT NOT NULL AUTO_INCREMENT,
	PlayerName VARCHAR(64) UNIQUE,
	Health INT NOT NULL DEFAULT 100,
	Money INT NOT NULL DEFAULT 0,
	GameTime INT NOT NULL DEFAULT 0,
	GameDay INT NOT NULL DEFAULT 0,
<<<<<<< HEAD
	PRIMARY KEY (Player_id),
	UNIQUE (PlayerName)
=======
	PRIMARY KEY (Player_id)
>>>>>>> aba6947f00c28937f653857617272d5894dee504
); 

CREATE TABLE IF NOT EXISTS Inventory ( 
	Item_id INT NOT NULL AUTO_INCREMENT,
	Player_id INT NOT NULL,
	ItemName VARCHAR(32) NOT NULL,
	PRIMARY KEY (Item_id),
	FOREIGN KEY (Player_id) REFERENCES Players(Player_id)
);

CREATE TABLE IF NOT EXISTS Items ( 
	Item_id INT NOT NULL AUTO_INCREMENT,
	ItemName VARCHAR(32) NOT NULL,
	PRIMARY KEY (Item_id)
);

<<<<<<< HEAD


=======
TRUNCATE TABLE Items;
TRUNCATE TABLE Players;
>>>>>>> aba6947f00c28937f653857617272d5894dee504
-- INSERT INTO TABLE Items (ItemName)
-- VALUES (
--	"Axe", "Knife", "etc..."
-- );
